### ISSUE TITLE
Asking about network isolation for VPS 

### ISSUE THREAD

**Issue by NghiaNguyen170192** [roachfire/roachlab#7]
Hi, 

I'm currently following your guide to setup my self host VPS. 
The idea is to have a nginx proxy manager as a reverse proxy to all applications on my VPS. 

As I follow along your guide, I see that when running `docker-compose up -d`, my VPS also exposes ports to the Internet and can be access via `http://ip-address:port`.

Is there a way to 
1. Configure all applications sit behind `nginx proxy manager`?
2. Disallow all public ports, only allow `80`, `443` publicly (from VPS network, docker network, ....)?
3. Once an user enter a domain on browser, the `nginx proxy manager` can route to the exact `host name` and the `port`?

**Comment by roachfire** [comment]
Hey! I don't have experience with your particular setup, but I'll try to provide some insight. 

1 and 2 are solved by the same thing I believe. Disable inbound traffic to the VPS unless it's coming from port 80 or 443 using either the host OS' built-in firewall or the one provided in your VPS' management dashboard (if it has one). If you want to further restrict access you can look at using NPM's built-in ACLs that allow you to set passwords for access and/or limit access to a specific set of IPs.

3. If you're using Cloudflare for DNS and have a domain, the rest of the guide will tackle this part.
